<?php

namespace SMTC\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    public function findByProvinceId($province_id)
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT city
            FROM MainBundle:City city
            LEFT JOIN city.province province
            WHERE province.id = :province_id
        ")->setParameter('province_id', $province_id);

        return $query->getResult();
    }
}
