<?php

namespace SMTC\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use SMTC\MainBundle\Entity\Country;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUsersWithAddressesIn(Country $country)
    {
        $subQuery = $this->getEntityManager()->createQuery("
            SELECT address
            FROM MainBundle:Address address
            LEFT JOIN address.user user
            LEFT JOIN address.city city
            LEFT JOIN city.province province
            LEFT JOIN province.country country
            WHERE country.id = :country_id AND user.id = u.id
        ");

        $queryBuilder = $this->createQueryBuilder('u');
        $queryBuilder
            ->where($queryBuilder->expr()->exists($subQuery->getDql()))
            ->setParameter('country_id', $country->getId());

        return $queryBuilder->getQuery()->getResult();
    }

    public function findUsersWithAllAddressesIn(Country $country)
    {
        $subQuery = $this->getEntityManager()->createQuery("
            SELECT address
            FROM MainBundle:Address address
            LEFT JOIN address.user user
            LEFT JOIN address.city city
            LEFT JOIN city.province province
            LEFT JOIN province.country country
            WHERE country.id != :country_id AND user.id = u.id
        ");

        $queryBuilder = $this->createQueryBuilder('u');
        $queryBuilder
            ->where($queryBuilder->expr()->not($queryBuilder->expr()->exists($subQuery->getDql())))
            ->setParameter('country_id', $country->getId());

        return $queryBuilder->getQuery()->getResult();
    }
}
